kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../base

patchesJson6902:
  - path: patch-channel-csv.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: cluster-kube-descheduler-operator
      version: v1alpha1
