kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../cluster-config/sealed-secrets-operator/overlays/lab
  - ../../cluster-config/oauth/overlays/htpasswd
  - ../../cluster-config/groups-roles-bindings/base
  - ../../cluster-config/descheduler/base
  - ../../cluster-config/container-security-operator/overlays/quay-3.5
  - ../../cluster-config/pipeline-operator/overlays/stable
  - ../../apps/cerberus/base
  - ../../apps/benchmark-operator/base
