apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgACESW7su+mRq3jaUk/J9rqH/1oFrc32aWiClIg4tNZ8RY3WTqRBUGFLoMxNBRWXnqWNrsrVHVyL/37K9qhqZNLbGo90mBNKPkrMrUmD6cVtilfP6e02MskELHCWLwizqsY+OspfPENvyobYed6sqPNKcDUHv17iELlJTfEV5Dd3tPGZdAzB3Ei3RFft+KMtPpokV5z010Ji01yKBF4IfrAzBwd3e9lmSDQImhtCpX6Jg/vHbr7lbxN7keRSMllGUyy1dXc5e1k/u0nnHxx7JLxlLecSthel+5uQAJUIJF7HwoEH3tBJukhYg8Mi8tZzMvfKcRkmZhFjZ94uxrD3t74XpYxJwFesiPEL/OYC0tUuR6HYMpIAUPCP4fg42sHIIyGgJlNABTP+tO/L2lCOpwnAkgSuJjijY8NQRivEB2m3H7YGEwJktHmytxvx9lekd9n0Lu9v0v81DuP7Ceb8Hp0ecXxg3JUaAXus08hfdIDUY3/14Dcf+V5LlMnRjONXC1xtGQInJl82ER6W26GkAGOlh0pVcltQw1QtbwWYu2pm2JzlZays+dtRUgo1qXRGg6WCy4WN6BESji5ALAF0bXq1YkUMT2E67Hk8P3nZiRCzb3pDVQtgZXu+fNsxpoY3ld2ITcrK9jexIzZmi+TOmeWLMRh3HLAEN0aPRWBnPTOpMuQoAq9A0+jBGZtjSGOQ1gor80xzfoSndQK44rXMcG0dcLHNA4yKqBaeRu9NnjMEVIzAsa9X4pPWWB/Wmm6MLFGRJ81A5aPlvIc+ZTK4ymWw2Feb9XdTqNKSA96Fp4SmJr1LjouBEVkEEGkbpTJqyOq91y1iMrPj/VcDpxoRq3B8Fzk1snsFExMOg+spXwHUyyovqF7
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

