apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JEZKc2FYb3JzZldQMHRsa1hqWmVpT2VJOE11NDNhbUJBdXZMV3hoa0xMTlBOQVNkajhTL3dXCmRldjE6JDJ5JDA1JGpKakJyNXFtVHNCTDQ5bTNnb3NqeGVJNVNpNnY4cGZjL1FQYkJFalY1QVp0ZW1aSDlxZE1tCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
