kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Canada GitOps repo (unofficial).
resources:
  - github.com/redhat-canada-gitops/catalog/compliance-operator/overlays/4.7?ref=master

patchesJson6902:
  - path: patch-version-csv.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: compliance-operator
      version: v1alpha1