kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app: benchmark-operator

namespace: my-ripsaw

resources:
  - ripsaw-namespace.yaml
  - ripsaw-crd.yaml
  - ripsaw-operator.yaml
  - ripsaw-psp.yaml
  - ripsaw-role-binding.yaml
  - ripsaw-role.yaml
  - ripsaw-service-account.yaml
