kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app: cerberus

namespace: cerberus

resources:
  - cerberus-namespace.yaml
  - cerberus-service-account.yaml
  - cerberus-role-binding.yaml
  - cerberus-deployment.yaml
  - cerberus-service.yaml
  - cerberus-route.yaml

configMapGenerator:
  - name: cerberus-config
    behavior: create
    files:
    - config.yaml=config-template.yaml
  - name: kube-config
    behavior: create
    files:
      - config=kubeconfig