kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Container CoP GitOps catalog repo (unofficial).
bases:
  - github.com/redhat-cop/gitops-catalog/sealed-secrets-operator/overlays/default?ref=main

resources:
  - namespace.yaml
  - role-anyuid.yaml

images:
  - name: quay.io/bitnami/sealed-secrets-controller
    newTag: v0.16.0
