kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Canada GitOps repo (unofficial).
bases:
  - github.com/redhat-canada-gitops/catalog/sealed-secrets-operator/overlays/default?ref=master

resources:
  - namespace.yaml
  - role-anyuid.yaml

images:
  - name: quay.io/bitnami/sealed-secrets-controller
    newTag: v0.16.0
